version: '3'
services:
  appServer:
    image: "anteoy/app_server:v0.9.2"
    ports:
     - "8080:8080"
    links:
     - mongodb
     - mysql
    environment:
     - liongo_env=compose
  mongodb:
    image: "mongo:3.2.18"
    volumes:
      - mongo_data:/data/db
  mysql:
    image: "mysql:5.7.21"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123