version: '3'
services:
  appServer:
    image: "anteoy/app_server:v0.9.1"
    ports:
     - "8080:8080"
    links:
     - mongodb
     - mysql
  mongodb:
    image: "mongo:3.2.18"
  mysql:
    image: "mysql:5.7.21"
    environment:
      - MYSQL_ROOT_PASSWORD=123